#' Match Performance Metrics to Data Types
#'
#' @param report_mdufa_period Text string defining whether the data is coming
#'   from a MDUFA III, MDUFA IV, or MDUFA V report. Currently defaults to
#'   \code{"MDUFA IV"}.
#' @return A table with common performance metrics in the first column and
#'   metric types (e.g. integer, percent, etc.) in the second column.
#' @export
#'
metric_types <- function(report_mdufa_period = "MDUFA IV") {
  if (report_mdufa_period == "MDUFA IV") {
    ## MDUFA IV ---------
    tibble::tribble(
      ~performance_metric, ~metric_type,
      "20th Percentile FDA Days to MDUFA IV Decision", "integer",
      "20th Percentile FDA Days to Substantive Interaction", "integer",
      "20th Percentile FDA Days to Written Feedback", "integer",
      "20th Percentile Industry Days to MDUFA IV Decision", "integer",
      "20th Percentile Total Days to MDUFA IV Decision", "integer",
      "40th Percentile FDA Days to MDUFA IV Decision", "integer",
      "40th Percentile FDA Days to Substantive Interaction", "integer",
      "40th Percentile FDA Days to Written Feedback", "integer",
      "40th Percentile Industry Days to MDUFA IV Decision", "integer",
      "40th Percentile Total Days to MDUFA IV Decision", "integer",
      "510(k) Accepted", "integer",
      "510(k)s Accepted", "integer",
      "510(k)s NSE Without SI", "integer",
      "510(k)s Pending MDUFA IV Decision", "integer",
      "510(k)s Pending MDUFA IV Decision Over 90 FDA Days", "integer",
      "60th Percentile FDA Days to MDUFA IV Decision", "integer",
      "60th Percentile FDA Days to Substantive Interaction", "integer",
      "60th Percentile FDA Days to Written Feedback", "integer",
      "60th Percentile Industry Days to MDUFA IV Decision", "integer",
      "60th Percentile Total Days to MDUFA IV Decision", "integer",
      "80th Percentile FDA Days to MDUFA IV Decision", "integer",
      "80th Percentile FDA Days to Substantive Interaction", "integer",
      "80th Percentile FDA Days to Written Feedback", "integer",
      "80th Percentile Industry Days to MDUFA IV Decision", "integer",
      "80th Percentile Total Days to MDUFA IV Decision", "integer",
      "Average Days to Scheduling for Meetings Scheduled After Day 30",
      "double",
      "Average FDA Days to MDUFA IV Decision", "double",
      "Average FDA Days to Written Feedback", "double",
      "Average Industry Days to MDUFA IV Decision", "double",
      paste0(
        "Average Number of Amendments Prior to IDE Approval or ",
        "Conditional Approval"
      ), "double",
      "Average Number of Cycles to IDE Approval or Conditional Approval",
      "double",
      "Average Number of FDA Days to MDUFA IV Decision", "double",
      "Average Number of FDA Days to Substantive Interaction", "double",
      "Average Number of Industry Days to MDUFA IV Decision", "double",
      "Average Number of Total Days to MDUFA IV Decision", "double",
      "Average Review Cycles", "double",
      "Average Total Days to MDUFA IV Decision", "double",
      "Closed Before RTA Action", "integer",
      "Closed Before RTA Action**", "integer",
      "Closed Without SI", "integer",
      "Completed RTF", "integer",
      "Current Performance Percent Goal Met", "percent",
      "Current Performance Percent Within 150 FDA Days", "percent",
      "Current Performance Percent Within 90 FDA Days", "percent",
      "Current SI Performance Percent Goal Met", "percent",
      "Current SI Performance Percent Within 60 FDA Days", "percent",
      "De Novos Accepted", "integer",
      "De Novos Pending MDUFA IV Decision", "integer",
      "De Novos Pending MDUFA IV Decision Over 150 FDA Days", "integer",
      "Deleted or Withdrawn Prior to SI", "integer",
      "Eligible for SI", "integer",
      "Maximum FDA Days to MDUFA IV Decision", "integer",
      "Maximum FDA Days to Substantive Interaction", "integer",
      "Maximum FDA Days to Written Feedback", "integer",
      "Maximum Industry Days to MDUFA IV Decision", "integer",
      "Maximum Total Days to MDUFA IV Decision", "integer",
      "MDUFA IV Decision", "integer",
      "MDUFA IV Decision (SE/NSE)", "integer",
      "MDUFA IV Decision Goal Met", "integer",
      "MDUFA IV Decision Within 90 FDA Days", "integer",
      "MDUFA IV Decisions", "integer",
      "MDUFA IV Decisions Within 150 FDA Days", "integer",
      "Mean FDA Days for Submissions that Missed the Goal", "double",
      "Mean Industry Days for Submissions that Missed the Goal", "double",
      "Meeting Held", "integer",
      "Meeting Minutes Not Submitted and <= 15 Days Since Meeting Date",
      "integer",
      "Meeting Minutes Not Submitted and >15 Days Since Meeting", "integer",
      "Meeting Minutes Past 15 Days of Meeting", "integer",
      "Meeting Minutes Submitted Within 15 Days of Meeting", "integer",
      "Meetings Not Scheduled By Day 30", "integer",
      "Non-MDUFA IV Decision", "integer",
      "Non-MDUFA IV Decisions", "integer",
      "Number Accepted", "integer",
      "Number Accepted First RTA Cycle", "integer",
      "Number Accepted First RTA Cycle**", "integer",
      "Number Deleted", "integer",
      "Number Filed", "integer",
      "Number Not Accepted", "integer",
      "Number Not Accepted for Filing Review", "integer",
      "Number Not Filed", "integer",
      "Number of Deleted", "integer",
      "Number of IDEs Received", "integer",
      "Number of Not Approvable", "integer",
      "Number of NSE Decision", "integer",
      "Number of PMAs Filed", "integer",
      "Number of SE Decision", "integer",
      "Number of Submissions that Missed the Goal", "integer",
      "Number of Substantive Interaction", "integer",
      "Number of Substantive Interactions", "integer",
      "Number of Withdrawal", "integer",
      "Number of Withdrawals", "integer",
      "Number Received", "integer",
      "Number with Accepted RTA Review", "integer",
      "Number With Declined Decisions", "integer",
      "Number With Granted Decisions", "integer",
      "Number with MDUFA IV Decision", "integer",
      "Number With MDUFA IV Decision", "integer",
      "Number With MDUFA IV Decisions", "integer",
      "Number Without a RTA Review and <= 15 Days Since Date Received",
      "integer",
      "Number Without a RTA Review and > 15 Days Since Date Received",
      "integer",
      "Number Without a RTA Review and > 15 Days Since Date Received**",
      "integer",
      "Performance Metric", "text",
      "Performance Metric ", "text",
      "PMAs Pending MDUFA IV Decision", "integer",
      "PMAs Pending MDUFA IV Decision Past Goal", "integer",
      "Rate of Declined Decisions", "percent",
      "Rate of Deleted", "percent",
      "Rate of Granted Decisions", "percent",
      "Rate of Not Approvable", "percent",
      "Rate of NSE Decision", "percent",
      "Rate of SE Decision", "percent",
      "Rate of Submissions Not Accepted for Filing Review", "percent",
      "Rate of Submissions Not Accepted for Review", "percent",
      "Rate of Submissions Not Filed", "percent",
      "Rate of Withdrawal", "percent",
      "Rate of Withdrawals", "percent",
      "SI Goal Met", "integer",
      "SI Goal Not Met", "integer",
      "SI Over 60 FDA Days", "integer",
      "SI Pending Over 60 FDA Days", "integer",
      "SI Pending Past Goal", "integer",
      "SI Pending Within 60 FDA Days", "integer",
      "SI Pending Within Goal", "integer",
      "SI Within 60 FDA Days", "integer",
      "Substantive Interaction (SI) Goal", "text",
      "Supplements Pending MDUFA IV Decision", "integer",
      "Supplements Pending MDUFA IV Decision Past Goal", "integer",
      "Supplements Received", "integer",
      "Which Industry Provided Minutes Within 15", "percent",
      "Written Feedback Sent", "integer",
      # Anual report metrics
      "Premarket Report Submissions", "integer",
      "Original PMAs (Panel) - Breakthrough Device", "integer",
      "Original PMAs (No Panel) - Breakthrough Device", "integer",
      "Original PMAs (Panel) - Non-Breakthrough Device", "integer",
      "Original PMAs (No Panel) - Non-Breakthrough Device", "integer",
      "Panel-Tracked Supplements (Panel) - Breakthrough Device", "integer",
      "Panel-Tracked Supplements (No Panel) - Breakthrough Device", "integer",
      "Panel-Tracked Supplements (Panel) - Non- Breakthrough Device", "integer",
      "Panel-Tracked Supplements (No Panel) - Non- Breakthrough Device",
      "integer",
      "PMA Modules", "integer",
      "180-Day Supplements", "integer",
      "Real-Time Supplements", "integer",
      "Number With a Decision (MDUFA or Non- MDUFA)", "integer",
      "% of FY Closed", "percent",
      "Number With a MDUFA Decision", "integer",
      "Number With a MDUFA Decision After Trimming the Upper and Lower 5%",
      "integer",
      "Three-year Rolling Average Total Time to MDUFA Decision", "double",
      "Number of Traditional Submissions", "integer",
      "Number of Special Submissions", "integer",
      "Number of Abbreviated Submissions", "integer",
      "Average Number of Days to Accept/Refuse to Accept", "double",
      "Number of Third Party Submissions", "integer",
      "Currently Under Review", "integer",
      "Number With Non-MDUFA IV Decision", "integer",
      "Percent of Cohort Closed", "percent",
      "Number With MDUFA IV Decision After Trimming the Upper and Lower 2%",
      "integer",
      "Average Total Time to MDUFA IV Decision", "double",
      "90th Percentile FDA Days to MDUFA IV Decision", "integer",
      "Average Number of Days to Accept / Refuse to Accept*", "double",
      "Substantive Interaction (SI) Goals:", "text",
      "Withdrawn prior to SI", "integer",
      "SI within 90 FDA days", "integer",
      "SI over 90 FDA days", "integer",
      "SI pending within 90 FDA days", "integer",
      "SI pending over 90 FDA days", "integer",
      "Denial without SI", "integer",
      "Current SI Performance Percent within 90 FDA days*", "percent",
      "Average number of FDA days to Substantive Interaction", "double",
      "20th Percentile FDA days to Substantive Interaction", "integer",
      "40th Percentile FDA days to Substantive Interaction", "integer",
      "60th Percentile FDA days to Substantive Interaction", "integer",
      "80th Percentile FDA days to Substantive Interaction", "integer",
      "Maximum FDA days to Substantive Interaction", "integer",
      # TODO: Rather than handle the non-ascii dash character, I should probably
      # strip it from the string at the outset.
      "Original PMAs (Panel) \\032 Priority", "integer",
      "Original PMAs (No Panel) \\032 Priority", "integer",
      "Original PMAs (Panel) \\032 Non-Priority", "integer",
      "Original PMAs (No Panel) \\032 Non-Priority", "integer",
      "Panel-Tracked Supplements (Panel) \\032 Priority", "integer",
      "Panel-Tracked Supplements (No Panel) \\032 Priority", "integer",
      "Panel-Tracked Supplements (Panel) \\032 Non- Priority", "integer",
      "Panel-Tracked Supplements (No Panel) \\032 Non- Priority", "integer",
      "Number with a decision (MDUFA or Non- MDUFA)", "integer",
      "% of FY closed", "percent"
    )
  } else if (report_mdufa_period == "MDUFA III") {
    ## MDUFA III -------
    tibble::tribble(
      ~performance_metric, ~metric_type,
      "Completed RTF", "integer",
      "Current Performance Percent Goal Met", "percent",
      "Current SI Performance Percent Goal Met", "percent",
      "Eligible for SI", "integer",
      "Number Accepted", "integer",
      "Number Filed", "integer",
      "Number Not Accepted", "integer",
      "Number Not Accepted for Filing Review", "integer",
      "Number Not Filed", "integer",
      "Number of Not Approvable", "integer",
      "Number of Substantive Interactions", "integer",
      "Number of Withdrawals", "integer",
      "Number Received", "integer",
      "Performance Metric", "text",
      "Rate of Deleted", "percent",
      "Rate of Not Approvable", "percent",
      "Rate of Withdrawals", "percent",
      "SI Goal Met", "integer",
      "SI Goal Not Met", "integer",
      "SI Pending Past Goal", "integer",
      "SI Pending Within Goal", "integer",
      "Substantive Interaction (SI) Goal", "text",
      "Premarket Report Submissions", "integer",
      "PMA Modules", "integer",
      "180-Day Supplements", "integer",
      "Real-Time Supplements", "integer",
      "Currently Under Review", "integer",
      "Substantive Interaction (SI) Goals:", "text",
      "SI within 90 FDA days", "integer",
      "SI over 90 FDA days", "integer",
      "SI pending within 90 FDA days", "integer",
      "SI pending over 90 FDA days", "integer",
      "Average number of FDA days to Substantive Interaction", "double",
      "20th Percentile FDA days to Substantive Interaction", "integer",
      "40th Percentile FDA days to Substantive Interaction", "integer",
      "60th Percentile FDA days to Substantive Interaction", "integer",
      "80th Percentile FDA days to Substantive Interaction", "integer",
      "Maximum FDA days to Substantive Interaction", "integer",
      "Number with a decision (MDUFA or Non- MDUFA)", "integer",
      "% of FY closed", "percent",
      # Everything above this line consistent with MDUFA 4
      "Closed before RTA action", "integer",
      "Number with accepted RTA review", "integer",
      "Number without a RTA Review and > 15 Days since Date Received",
      "integer",
      "Number without a RTA Review and <= 15 Days since Date Received",
      "integer",
      "Rate of submissions not accepted for filing review", "percent",
      "Rate of submissions Not Filed", "percent",
      "Closed without SI", "integer",
      "Average number of FDA days to Substantive", "double",
      "20th Percentile FDA days to Substantive", "integer",
      "40th Percentile FDA days to Substantive", "integer",
      "60th Percentile FDA days to Substantive", "integer",
      "80th Percentile FDA days to Substantive", "integer",
      "Interaction Maximum FDA days to Substantive Interaction", "integer",
      "Number of PMAs filed", "integer",
      "Non-MDUFA III Decisions", "integer",
      "MDUFA III Decisions", "integer",
      "MDUFA III Decisions Goal Met", "integer",
      "PMAs pending MDUFA III Decision", "integer",
      "PMAs pending MDUFA III Decision Past Goal", "integer",
      "Number with MDUFA III decision", "integer",
      "Average FDA days to MDUFA III decision", "double",
      "20th Percentile FDA days to MDUFA III decision", "integer",
      "40th Percentile FDA days to MDUFA III decision", "integer",
      "60th Percentile FDA days to MDUFA III decision", "integer",
      "80th Percentile FDA days to MDUFA III decision", "integer",
      "Maximum FDA days to MDUFA III decision", "integer",
      "Average Industry days to MDUFA III decision", "double",
      "20th Percentile Industry days to MDUFA III decision", "integer",
      "40th Percentile Industry days to MDUFA III decision", "integer",
      "60th Percentile Industry days to MDUFA III decision", "integer",
      "80th Percentile Industry days to MDUFA III decision", "integer",
      "Maximum Industry days to MDUFA III decision", "integer",
      "Average Total days to MDUFA III decision", "double",
      "20th Percentile Total days to MDUFA III decision", "integer",
      "40th Percentile Total days to MDUFA III decision", "integer",
      "60th Percentile Total days to MDUFA III decision", "integer",
      "80th Percentile Total days to MDUFA III decision", "integer",
      "Maximum Total days to MDUFA III decision", "integer",
      "Number with MDUFA decision", "integer",
      "Number of submissions that missed the goal", "integer",
      "Mean FDA days for submissions that missed goal", "double",
      "Mean industry days for submissions that missed goal", "double",
      "Substantive Interaction", "double",
      "Substantive Interaction (SI) Goals:", "text",
      "Supplements received", "integer",
      "Supplements pending MDUFA III Decision", "integer",
      "Supplements pending MDUFA III Decision Past Goal", "integer",
      "Mean Industry days for submissions that missed goal", "double",
      "Original PMAs (Panel) \u2013 Priority", "integer",
      "Original PMAs (No Panel) \u2013 Priority", "integer",
      "Original PMAs (Panel) \u2013 Non-Priority", "integer",
      "Original PMAs (No Panel) \u2013 Non-Priority", "integer",
      "Panel-Tracked Supplements (Panel) \u2013 Priority", "integer",
      "Panel-Tracked Supplements (No Panel) \u2013 Priority", "integer",
      "Panel-Tracked Supplements (Panel) \u2013 Non- Priority", "integer",
      "Panel-Tracked Supplements (No Panel) \u2013 Non- Priority", "integer",
      "Deleted or withdrawn prior to SI", "integer",
      "SI within 60 FDA days", "integer",
      "SI over 60 FDA days", "integer",
      "SI pending within 60 FDA days", "integer",
      "SI pending over 60 FDA days", "integer",
      "510(k)s NSE without SI", "integer",
      "Current SI Performance Percent within 60 FDA days", "percent",
      "510(k)s accepted", "integer",
      "MDUFA III Decisions (SE/NSE)", "integer",
      "MDUFA III Decisions within 90 FDA Days", "integer",
      "510(k)s pending MDUFA III Decision", "integer",
      "510(k) pending MDUFA III Decision over 90 FDA days", "integer",
      "Current Performance Percent within 90 FDA Days", "percent",
      "Average review cycles", "double",
      "20th Percentile FDA days to MDUFA III", "integer",
      "40th Percentile FDA days to MDUFA III", "integer",
      "60th Percentile FDA days to MDUFA III", "integer",
      "80th Percentile FDA days to MDUFA III", "integer",
      "decision Maximum FDA days to MDUFA III decision", "integer",
      "Average Industry days to MDUFA III", "double",
      "20th Percentile Industry days to MDUFA III", "integer",
      "40th Percentile Industry days to MDUFA III", "integer",
      "60th Percentile Industry days to MDUFA III", "integer",
      "80th Percentile Industry days to MDUFA III", "integer",
      "decision Maximum Industry days to MDUFA III decision", "integer",
      "20th Percentile Total days to MDUFA III", "integer",
      "40th Percentile Total days to MDUFA III", "integer",
      "60th Percentile Total days to MDUFA III", "integer",
      "80th Percentile Total days to MDUFA III", "integer",
      "Number of SE decisions", "integer",
      "Number of NSE decisions", "integer",
      "Number deleted", "integer",
      "Rate of SE decisions", "percent",
      "Rate of NSE decisions", "percent",
      "Number of Traditional submissions", "integer",
      "Number of Special submissions", "integer",
      "Number of Abbreviated submissions", "integer",
      "Average number of days to Accept / Refuse to Accept", "double",
      "Number of Third Party submissions", "integer",
      "Number with Non-MDUFA Decision", "integer",
      "Number with MDUFA III Decision", "integer",
      "Percent of cohort closed", "percent",
      "Number with MDUFA III decision after trimming the upper and lower 2%",
      "integer",
      "Average Total Time to MDUFA III decision", "double",
      "Number of De Novo Requests Received", "integer",
      "Number of De Novo Requests with Decision", "integer",
      "Number of De Novo Requests with Decision Pending", "integer",
      "Average Number of Days to Decision", "double",
      "Number of all qualified Pre-Submissions received", "integer",
      "Number requesting a meeting or teleconference", "integer",
      "Number with meetings or teleconferences held", "integer",
      "Average days to meeting", "double",
      "20th Percentile days to meeting", "integer",
      "40th Percentile days to meeting", "integer",
      "60th Percentile days to meeting", "integer",
      "80th Percentile days to meeting", "integer",
      "Maximum days to meeting", "integer",
      "Current SI Performance Percent within 90 FDA days", "percent",
      "MDUFA III Decisions within 180 FDA Days", "integer",
      "PMAs pending MDUFA III Decision over 180 FDA days", "integer",
      "Days", "percent", # Maybe integer
      "MDUFA III Decisions within 320 FDA Days", "integer",
      "PMAs pending MDUFA III Decision over 320 FDA days", "integer",
      "Supplements pending MDUFA III Decision over 180 FDA days", "integer",
      "Supplements pending MDUFA III Decision over 90 FDA days", "integer",
      "Panel-Tracked Supplements (No Panel) \u2013 Non-Priority", "integer",
      "Rate of submissions not accepted for review", "percent",
      "Number of De Novo Petitions Received", "integer",
      "Number of De Novo Petitions with Decision", "integer",
      "Number of De Novo Petitions with Decision Pending", "integer",
      "Number with meetings or teleconferences granted", "integer",
      "Number with meeting granted and industry cancelled", "integer",
      "Number with meeting granted and FDA cancelled", "integer",
      "Number with meeting granted and pending within timeframe", "integer",
      "Number with meeting granted and pending outside timeframe", "integer"
    )
  } else if (report_mdufa_period == "MDUFA V") {
    ## MDUFA V -----
    tibble::tribble(
      ~performance_metric, ~metric_type,
      "20th Percentile FDA Days to MDUFA V Decision", "integer",
      "20th Percentile FDA Days to Substantive Interaction", "integer",
      "20th Percentile FDA Days to Written Feedback", "integer",
      "20th Percentile Industry Days to MDUFA V Decision", "integer",
      "20th Percentile Total Days to MDUFA V Decision", "integer",
      "40th Percentile FDA Days to MDUFA V Decision", "integer",
      "40th Percentile FDA Days to Substantive Interaction", "integer",
      "40th Percentile FDA Days to Written Feedback", "integer",
      "40th Percentile Industry Days to MDUFA V Decision", "integer",
      "40th Percentile Total Days to MDUFA V Decision", "integer",
      "510(k) Accepted", "integer",
      "510(k)s Accepted", "integer",
      "510(k)s NSE Without SI", "integer",
      "510(k)s Pending MDUFA V Decision", "integer",
      "510(k)s Pending MDUFA V Decision Over 90 FDA Days", "integer",
      "60th Percentile FDA Days to MDUFA V Decision", "integer",
      "60th Percentile FDA Days to Substantive Interaction", "integer",
      "60th Percentile FDA Days to Written Feedback", "integer",
      "60th Percentile Industry Days to MDUFA V Decision", "integer",
      "60th Percentile Total Days to MDUFA V Decision", "integer",
      "80th Percentile FDA Days to MDUFA V Decision", "integer",
      "80th Percentile FDA Days to Substantive Interaction", "integer",
      "80th Percentile FDA Days to Written Feedback", "integer",
      "80th Percentile Industry Days to MDUFA V Decision", "integer",
      "80th Percentile Total Days to MDUFA V Decision", "integer",
      "Average Days to Scheduling for Meetings Scheduled After Day 30",
      "double",
      "Average FDA Days to MDUFA V Decision", "double",
      "Average FDA Days to Written Feedback", "double",
      "Average Industry Days to MDUFA V Decision", "double",
      paste0(
        "Average Number of Amendments Prior to IDE Approval or ",
        "Conditional Approval"
      ), "double",
      "Average Number of Cycles to IDE Approval or Conditional Approval",
      "double",
      "Average Number of FDA Days to MDUFA V Decision", "double",
      "Average Number of FDA Days to Substantive Interaction", "double",
      "Average Number of Industry Days to MDUFA V Decision", "double",
      "Average Number of Total Days to MDUFA V Decision", "double",
      "Average Review Cycles", "double",
      "Average Total Days to MDUFA V Decision", "double",
      "Closed Before RTA Action", "integer",
      "Closed Before RTA Action**", "integer",
      "Closed Without SI", "integer",
      "Completed RTF", "integer",
      "Current Performance Percent Goal Met", "percent",
      "Current Performance Percent Within 150 FDA Days", "percent",
      "Current Performance Percent Within 90 FDA Days", "percent",
      "Current SI Performance Percent Goal Met", "percent",
      "Current SI Performance Percent Within 60 FDA Days", "percent",
      "De Novos Accepted", "integer",
      "De Novos Pending MDUFA V Decision", "integer",
      "De Novos Pending MDUFA V Decision Over 150 FDA Days", "integer",
      "Deleted or Withdrawn Prior to SI", "integer",
      "Eligible for SI", "integer",
      "Maximum FDA Days to MDUFA V Decision", "integer",
      "Maximum FDA Days to Substantive Interaction", "integer",
      "Maximum FDA Days to Written Feedback", "integer",
      "Maximum Industry Days to MDUFA V Decision", "integer",
      "Maximum Total Days to MDUFA V Decision", "integer",
      "MDUFA V Decision", "integer",
      "MDUFA V Decision (SE/NSE)", "integer",
      "MDUFA V Decision Goal Met", "integer",
      "MDUFA V Decision Within 90 FDA Days", "integer",
      "MDUFA V Decisions", "integer",
      "MDUFA V Decisions Within 150 FDA Days", "integer",
      "Mean FDA Days for Submissions that Missed the Goal", "double",
      "Mean Industry Days for Submissions that Missed the Goal", "double",
      "Meeting Held", "integer",
      "Meeting Minutes Not Submitted and <= 15 Days Since Meeting Date",
      "integer",
      "Meeting Minutes Not Submitted and >15 Days Since Meeting", "integer",
      "Meeting Minutes Past 15 Days of Meeting", "integer",
      "Meeting Minutes Submitted Within 15 Days of Meeting", "integer",
      "Meetings Not Scheduled By Day 30", "integer",
      "Non-MDUFA V Decision", "integer",
      "Non-MDUFA V Decisions", "integer",
      "Number Accepted", "integer",
      "Number Accepted First RTA Cycle", "integer",
      "Number Accepted First RTA Cycle**", "integer",
      "Number Deleted", "integer",
      "Number Filed", "integer",
      "Number Not Accepted", "integer",
      "Number Not Accepted for Filing Review", "integer",
      "Number Not Filed", "integer",
      "Number of Deleted", "integer",
      "Number of IDEs Received", "integer",
      "Number of Not Approvable", "integer",
      "Number of NSE Decision", "integer",
      "Number of PMAs Filed", "integer",
      "Number of SE Decision", "integer",
      "Number of Submissions that Missed the Goal", "integer",
      "Number of Substantive Interaction", "integer",
      "Number of Substantive Interactions", "integer",
      "Number of Withdrawal", "integer",
      "Number of Withdrawals", "integer",
      "Number Received", "integer",
      "Number with Accepted RTA Review", "integer",
      "Number With Declined Decisions", "integer",
      "Number With Granted Decisions", "integer",
      "Number with MDUFA V Decision", "integer",
      "Number With MDUFA V Decision", "integer",
      "Number With MDUFA V Decisions", "integer",
      "Number Without a RTA Review and <= 15 Days Since Date Received",
      "integer",
      "Number Without a RTA Review and > 15 Days Since Date Received",
      "integer",
      "Number Without a RTA Review and > 15 Days Since Date Received**",
      "integer",
      "Performance Metric", "text",
      "Performance Metric ", "text",
      "PMAs Pending MDUFA V Decision", "integer",
      "PMAs Pending MDUFA V Decision Past Goal", "integer",
      "Rate of Declined Decisions", "percent",
      "Rate of Deleted", "percent",
      "Rate of Granted Decisions", "percent",
      "Rate of Not Approvable", "percent",
      "Rate of NSE Decision", "percent",
      "Rate of SE Decision", "percent",
      "Rate of Submissions Not Accepted for Filing Review", "percent",
      "Rate of Submissions Not Accepted for Review", "percent",
      "Rate of Submissions Not Filed", "percent",
      "Rate of Withdrawal", "percent",
      "Rate of Withdrawals", "percent",
      "SI Goal Met", "integer",
      "SI Goal Not Met", "integer",
      "SI Over 60 FDA Days", "integer",
      "SI Pending Over 60 FDA Days", "integer",
      "SI Pending Past Goal", "integer",
      "SI Pending Within 60 FDA Days", "integer",
      "SI Pending Within Goal", "integer",
      "SI Within 60 FDA Days", "integer",
      "Substantive Interaction (SI) Goal", "text",
      "Supplements Pending MDUFA V Decision", "integer",
      "Supplements Pending MDUFA V Decision Past Goal", "integer",
      "Supplements Received", "integer",
      "Which Industry Provided Minutes Within 15", "percent",
      "Written Feedback Sent", "integer",
      # Anual report metrics
      "Premarket Report Submissions", "integer",
      "Original PMAs (Panel) - Breakthrough Device", "integer",
      "Original PMAs (No Panel) - Breakthrough Device", "integer",
      "Original PMAs (Panel) - Non-Breakthrough Device", "integer",
      "Original PMAs (No Panel) - Non-Breakthrough Device", "integer",
      "Panel-Tracked Supplements (Panel) - Breakthrough Device", "integer",
      "Panel-Tracked Supplements (No Panel) - Breakthrough Device", "integer",
      "Panel-Tracked Supplements (Panel) - Non- Breakthrough Device", "integer",
      "Panel-Tracked Supplements (No Panel) - Non- Breakthrough Device",
      "integer",
      "PMA Modules", "integer",
      "180-Day Supplements", "integer",
      "Real-Time Supplements", "integer",
      "Number With a Decision (MDUFA or Non- MDUFA)", "integer",
      "% of FY Closed", "percent",
      "Number With a MDUFA Decision", "integer",
      "Number With a MDUFA Decision After Trimming the Upper and Lower 5%",
      "integer",
      "Three-year Rolling Average Total Time to MDUFA Decision", "double",
      "Number of Traditional Submissions", "integer",
      "Number of Special Submissions", "integer",
      "Number of Abbreviated Submissions", "integer",
      "Average Number of Days to Accept/Refuse to Accept", "double",
      "Number of Third Party Submissions", "integer",
      "Currently Under Review", "integer",
      "Number With Non-MDUFA V Decision", "integer",
      "Percent of Cohort Closed", "percent",
      "Number With MDUFA V Decision After Trimming the Upper and Lower 2%",
      "integer",
      "Average Total Time to MDUFA V Decision", "double",
      "90th Percentile FDA Days to MDUFA V Decision", "integer",
      "Average Number of Days to Accept / Refuse to Accept*", "double",
      "Substantive Interaction (SI) Goals:", "text",
      "Withdrawn prior to SI", "integer",
      "SI within 90 FDA days", "integer",
      "SI over 90 FDA days", "integer",
      "SI pending within 90 FDA days", "integer",
      "SI pending over 90 FDA days", "integer",
      "Denial without SI", "integer",
      "Current SI Performance Percent within 90 FDA days*", "percent",
      "Average number of FDA days to Substantive Interaction", "double",
      "20th Percentile FDA days to Substantive Interaction", "integer",
      "40th Percentile FDA days to Substantive Interaction", "integer",
      "60th Percentile FDA days to Substantive Interaction", "integer",
      "80th Percentile FDA days to Substantive Interaction", "integer",
      "Maximum FDA days to Substantive Interaction", "integer",
      # TODO: Rather than handle the non-ascii dash character, I should probably
      # strip it from the string at the outset.
      "Original PMAs (Panel) \\032 Priority", "integer",
      "Original PMAs (No Panel) \\032 Priority", "integer",
      "Original PMAs (Panel) \\032 Non-Priority", "integer",
      "Original PMAs (No Panel) \\032 Non-Priority", "integer",
      "Panel-Tracked Supplements (Panel) \\032 Priority", "integer",
      "Panel-Tracked Supplements (No Panel) \\032 Priority", "integer",
      "Panel-Tracked Supplements (Panel) \\032 Non- Priority", "integer",
      "Panel-Tracked Supplements (No Panel) \\032 Non- Priority", "integer",
      "Number with a decision (MDUFA or Non- MDUFA)", "integer",
      "% of FY closed", "percent",
      #### NEW -----
      "<= 15 Days Since Date Received (First RTA", "integer",
      "20th Percentile FDA Days to MDUFA Decision", "integer",
      "20th Percentile Industry Days to MDUFA Decision", "integer",
      "20th Percentile Total Days to MDUFA Decision", "integer",
      "40th Percentile FDA Days to MDUFA Decision", "integer",
      "40th Percentile Industry Days to MDUFA Decision", "integer",
      "40th Percentile Total Days to MDUFA Decision", "integer",
      "60th Percentile FDA Days to MDUFA Decision", "integer",
      "60th Percentile Industry Days to MDUFA Decision", "integer",
      "60th Percentile Total Days to MDUFA Decision", "integer",
      "80th Percentile FDA Days to MDUFA Decision", "integer",
      "80th Percentile Industry Days to MDUFA Decision", "integer",
      "80th Percentile Total Days to MDUFA Decision", "integer",
      "Average FDA Days to MDUFA Decision", "double",
      "Average Industry Days to MDUFA Decision", "double",
      "Average Total Days to MDUFA Decision", "double",
      "Closed Before First RTA or TS Action", "integer",
      "Days Since Date Received (First RTA Action", "integer",
      "De Novos Pending MDUFA Decision", "integer",
      "De Novos Pending MDUFA Decision Over 150 FDA Days", "integer",
      "De Novos Pending MDUFA IV Decision", "integer",
      "De Novos Pending MDUFA IV Decision Over 150 FDA Days", "integer",
      "Designated Products & Products", "integer",
      "Eligible For SI", "integer",
      "Maximum FDA Days to MDUFA Decision", "integer",
      "Maximum Industry Days to MDUFA Decision", "integer",
      "Maximum Total Days to MDUFA Decision", "integer",
      "MDUFA Decision", "integer",
      "MDUFA Decision Goal Met", "integer",
      "MDUFA Decision Within 150 FDA Days", "integer",
      "Mean FDA Days for Submissions That Missed the Goal", "double",
      "Mean Industry Days for Submissions That Missed the Goal", "double",
      "Non-MDUFA Decision", "integer",
      # "Number Accepted First RTA Cycle 1", "integer",
      "Number Accepted First RTA Cycle \u00B9", "integer",
      "Number Accepted First RTA Review", "integer",
      "Number Accepted or Passed TS on First Cycle", "integer",
      "Number Closed Before First RTA Action", "integer",
      "Number Not Accepted First RTA Cycle", "integer",
      "Number Not Accepted for Filing Review on First Cycle", "integer",
      "Number Not Accepted or Failed TS on First Cycle", "integer",
      "Number of Meetings Not Scheduled By Day 30", "integer",
      # "Number of Meetings Required 1", "integer",
      "Number of Meetings Required \u00B9", "integer",
      "Number With Declined Decision", "integer",
      "Number With Granted Decision", "integer",
      "Number with MDUFA Decision", "integer",
      "Number With MDUFA Decision", "integer",
      "Number with Written Feedback Sent", "integer",
      "Number Without a First Cycle RTA Review and <= 15 Days Since Date Received (First RTA Action Pending)", "integer", # nolint: line_length_linter.
      "Number Without a First Cycle RTA Review and > 15 Days Since Date Received*", "integer", # nolint: line_length_linter.
      "Number Without a RTA or TS Review and <= 15 Days Since Date Received", "integer", # nolint: line_length_linter.
      ##### TODO: FIX NON-ASCII Characters --------
      # "Number Without a RTA or TS Review and > 15 Days Since Date Received 1", "integer", # nolint: line_length_linter.
      "Number Without a RTA or TS Review and > 15 Days Since Date Received \u00B9", "integer", # nolint: line_length_linter.
      # "Number Without First Cycle RTA Review and > 15 Days Since Date Received 2", "integer", # nolint: line_length_linter.
      "Number Without First Cycle RTA Review and > 15 Days Since Date Received \u00B2", "integer", # nolint: line_length_linter.
      "Percent of Submissions With Meetings for Which Industry Provided Minutes Within 15 Days", "integer", # nolint: line_length_linter.
      "PMAs Pending MDUFA Decision", "integer",
      "PMAs Pending MDUFA Decision Past Goal", "integer",
      "Rate of Declined Decision", "percent",
      "Rate of Granted Decision", "percent",
      "Rate of Submissions Not Accepted for Filing Review on First Cycle", "percent", # nolint: line_length_linter.
      "Rate of Submissions Not Accepted for Review on First RTA Cycle", "percent", # nolint: line_length_linter.
      "Rate of Submissions Not Accepted for Review or Failed TS on First Cycle", "percent", # nolint: line_length_linter.
      "Supplements Pending MDUFA Decision", "integer",
      "Supplements Pending MDUFA Decision Past Goal", "integer",
      # Table 9.2 Pre-Sub Performance Goals metrics
      "Number Accepted / Eligible for MDUFA Action", "integer",
      "Number with Non-MDUFA Action \u00B3", "integer",
      "Number with MDUFA Action", "integer",
      "Written Feedback Provided Within Goal", "integer",
      "Number Pending MDUFA Action", "integer",
      "Pending MDUFA Action Past Goal", "integer",
      "Number in MDUFA Cohort (up to max 4300)\u2074", "integer",
      "Current Performance Percent Within Goal", "percent",
      # Table 9.1 Pre-Sub Acceptance Review Decision - multi-line metric
      paste0(
        "Interactions for Breakthrough Designated Products & Products ",
        "Included in STeP"
      ), "integer"
    )
  }
}
